name = "Casper"
license = "MIT"
licenselink = "https://github.com/vjeantet/hugo-theme-casper/blob/master/LICENSE.md"
description = "Casper theme from Ghost Foundation"
homepage = "http://kaselak.org/"
tags = ["blog"]
features = ["disqus", "google analytics","share"]
min_version=0.14

[author]
  name = "Gerald Kaselak"
  homepage = "http://Kaselak.org"

[original]
  name = "Casper"
  homepage = "https://Kaselak.org"
  repo = "https://github.com/TryGhost/Casper"
